// For Authentication
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

// For Player
export const PLAYER_FAIL = 'PLAYER_FAIL';
export const PLAYER_START = 'PLAYER_START';
export const PLAYER_SUCCESS = 'PLAYER_SUCCESS';
export const PLAYER_CHANGE_SONG = 'PLAYER_CHANGE_SONG';
export const PLAYER_CHANGE_PLAYLIST = 'PLAYER_CHANGE_PLAYLIST';
export const PLAYER_PLAYLIST_SONG_DETAILS = 'PLAYER_PLAYLIST_SONG_DETAILS';
export const PLAYER_GET_LIKE = 'PLAYER_GET_LIKE';
export const PLAYER_GET_COMMENT = 'PLAYER_GET_COMMENT';
export const PLAYER_TOGGLE_LIKE = 'PLAYER_TOGGLE_LIKE';
export const PLAYER_POST_COMMENT = 'PLAYER_POST_COMMENT';

//For Profile
export const PROFILE_START = 'PROFILE_START';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const PROFILE_USER_SONGS = 'PROFILE_USER_SONGS';
export const PROFILE_USER_PLAYLIST = 'PROFILE_USER_PLAYLIST';
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT';
export const PROFILE_SUCESS = 'PROFILE_SUCESS';
export const PROFILE_SUCESS_RESET = 'PROFILE_SUCESS_REST';
export const PROFILE_VIEW = 'PROFILE_VIEW';
