// For Authentication
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

// For Player
export const PLAYER_FAIL = 'PLAYER_FAIL';
export const PLAYER_START = 'PLAYER_START';
export const PLAYER_SUCCESS = 'PLAYER_SUCCESS';
export const PLAYER_CHANGE_SONG = 'PLAYER_CHANGE_SONG';
export const PLAYER_CHANGE_PLAYLIST = 'PLAYER_CHANGE_PLAYLIST';
export const PLAYER_PLAYLIST_SONG_DETAILS = 'PLAYER_PLAYLIST_SONG_DETAILS';
