# Generated by Django 3.1.2 on 2020-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_photo',
            field=models.ImageField(default='post_images/default.jpg', upload_to='songCover'),
        ),
    ]
