# Generated by Django 3.1.2 on 2020-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songs_song_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_photo',
            field=models.ImageField(default='songCover/default.jpg', upload_to='songCover'),
        ),
    ]
