# Generated by Django 3.1.2 on 2021-03-07 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_playlist_playlistdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 12, 39, 39, 509130)),
        ),
    ]
