# Generated by Django 3.1.2 on 2021-03-23 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_auto_20210323_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 14, 49, 54, 418069)),
        ),
    ]
