# Generated by Django 3.1.2 on 2021-03-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20210323_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 21, 55, 39, 579244)),
        ),
    ]
