# Generated by Django 3.1.2 on 2021-04-17 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_auto_20210323_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 19, 32, 4, 402228)),
        ),
    ]
