# Generated by Django 3.1.2 on 2021-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0020_auto_20210417_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
